-- Esquema de Base de Datos para Trivia Magica (Corregido para UUID)
-- Versión: 1.2 (Soporte UUID + Migración)

-- 1. Asegurar que las columnas nuevas existan en las tablas actuales (Migración)
DO $$ 
BEGIN
    -- Añadir state_version a rooms si no existe
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='rooms' AND column_name='state_version') THEN
        ALTER TABLE rooms ADD COLUMN state_version INTEGER NOT NULL DEFAULT 0;
    END IF;

    -- Añadir expires_at a rooms si no existe
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='rooms' AND column_name='expires_at') THEN
        ALTER TABLE rooms ADD COLUMN expires_at TIMESTAMPTZ;
    END IF;
END $$;

-- 2. Crear tabla de Respuestas Atómicas (usando el tipo de ID de la tabla rooms)
-- Nota: Usamos una subconsulta para detectar si rooms.id es UUID o BIGINT
DO $$
DECLARE
    room_id_type text;
BEGIN
    SELECT data_type INTO room_id_type 
    FROM information_schema.columns 
    WHERE table_name = 'rooms' AND column_name = 'id';

    IF room_id_type = 'uuid' THEN
        CREATE TABLE IF NOT EXISTS player_answers (
            id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
            room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,
            round_id TEXT NOT NULL,
            player_name TEXT NOT NULL,
            answer JSONB NOT NULL,
            elapsed_ms INTEGER,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE(room_id, round_id, player_name)
        );
    ELSE
        CREATE TABLE IF NOT EXISTS player_answers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
            round_id TEXT NOT NULL,
            player_name TEXT NOT NULL,
            answer JSONB NOT NULL,
            elapsed_ms INTEGER,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE(room_id, round_id, player_name)
        );
    END IF;
END $$;

-- 3. Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_rooms_code ON rooms(room_code);
CREATE INDEX IF NOT EXISTS idx_players_room ON players(room_id);
CREATE INDEX IF NOT EXISTS idx_answers_lookup ON player_answers(room_id, round_id);
