-- Esquema de Base de Datos para Trivia Magica
-- Versión: 1.1 (Estabilización Técnica)

-- Tabla de Salas (Rooms)
CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_code TEXT NOT NULL UNIQUE, -- Restricción UNIQUE (3.4)
  status TEXT NOT NULL DEFAULT 'lobby',
  game_state JSONB NOT NULL DEFAULT '{}',
  state_version INTEGER NOT NULL DEFAULT 0, -- Columna para Optimistic Locking (3.3)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ -- Sugerido para limpieza automática (3.15)
);

-- Tabla de Jugadores (Players)
CREATE TABLE IF NOT EXISTS players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  house TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(room_id, name) -- Restricción UNIQUE para evitar duplicados en la misma sala (3.4)
);

-- Tabla de Respuestas Atómicas (Opcional, recomendada en 4.3)
CREATE TABLE IF NOT EXISTS player_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  round_id TEXT NOT NULL,
  player_name TEXT NOT NULL,
  answer JSONB NOT NULL,
  elapsed_ms INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(room_id, round_id, player_name)
);

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_rooms_code ON rooms(room_code);
CREATE INDEX IF NOT EXISTS idx_players_room ON players(room_id);
