services:
  - type: web
    name: jackbox-magico-v2
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 20.x
