export const CALDERO_SCORING = {
  SURVIVED_GOOD: 120,
  SURVIVED_GOLD: 180,
  HOUSE_MOST_GOOD: 100,
  EXPLOSIVE_NOT_ACCUSED: 80,
  BAD_IN_EXPLOSION: 40,
  EXPLOSION_HOUSE_PENALTY: -50,
  ACCUSE_CORRECT_EXPLOSIVE: 90,
  ACCUSE_CORRECT_BAD: 40,
  ACCUSE_INCORRECT: -30,
  DISCARD_EXPLOSIVE: 60,
  NO_ACTION: -20
};
