"""Catálogo maestro con reglas, explicación y puntajes por minijuego."""

GAME_CATALOG = {
    "duelo_hechizos": {
        "name": "Duelo de Hechizos",
        "status": "implemented",
        "mode": "rps",
        "about": "Duelo rápido de contra-respuestas mágicas estilo piedra, papel o tijera.",
        "how_to_play": "Elige Protección, Contraataque o Esquivar antes que termine el tiempo.",
        "rules": [
            "Protección vence a Contraataque.",
            "Contraataque vence a Esquivar.",
            "Esquivar vence a Protección.",
            "Si empatan, no hay puntos.",
        ],
        "points": {"duel_winner": 100, "fastest_bonus": 25, "house_bonus": 50},
    },
    "sombrero_burlon": {
        "name": "Sombrero Burlón",
        "status": "implemented",
        "mode": "vote",
        "about": "Votación social donde el grupo decide quién encaja mejor con una situación chusca.",
        "how_to_play": "Lee la pregunta y vota por el jugador que mejor encaje.",
        "rules": [
            "No puedes votar fuera de los jugadores de la sala.",
            "Gana el jugador con más votos.",
            "Cada voto suma puntos al jugador votado.",
        ],
        "points": {"most_voted": 80, "vote_received": 10, "house_bonus": 50},
    },
    "clase_pociones": {
        "name": "Clase de Pociones",
        "status": "implemented",
        "mode": "memory",
        "about": "Recuerda recetas mágicas y detecta ingredientes correctos bajo presión.",
        "how_to_play": "Memoriza el orden de ingredientes y responde el paso faltante.",
        "rules": ["Acierto perfecto da puntaje completo.", "Error leve conserva puntos parciales."],
        "points": {"perfect": 100, "minor_error": 40, "fastest_perfect_bonus": 50},
    },
    "atrapa_snitch": {
        "name": "Atrapa la Snitch",
        "status": "implemented",
        "mode": "reaction",
        "about": "Juego de reflejos: toca solo en el instante correcto.",
        "how_to_play": "Cuando aparezca la señal válida, toca rápido. Evita trampas visuales.",
        "rules": ["Toque correcto suma.", "Toque falso resta puntos."],
        "points": {"first": 150, "second": 100, "third": 60, "false_tap": -30},
    },
    "trivia_magica": {
        "name": "Trivia del Mundo Mágico",
        "status": "implemented",
        "mode": "quiz",
        "about": "Preguntas del universo mágico con humor latino.",
        "how_to_play": "Selecciona la opción correcta entre cuatro respuestas.",
        "rules": ["Solo una respuesta es correcta.", "Dificultad define puntos."],
        "points": {"easy": 50, "medium": 100, "hard": 150},
    },
    "retratos_chismosos": {
        "name": "Retratos Chismosos",
        "status": "implemented",
        "mode": "quiz",
        "about": "Adivina personaje, lugar u objeto según pistas de retratos parlantes.",
        "how_to_play": "Lee la descripción y elige la opción que mejor coincide.",
        "rules": ["Respuesta correcta suma.", "Rápido y correcto puede tener bonus."],
        "points": {"correct": 100, "quick_bonus": 30},
    },
    "mapa_travieso": {
        "name": "El Mapa Travieso",
        "status": "implemented",
        "mode": "memory",
        "about": "Memoria espacial dentro del castillo y sus zonas misteriosas.",
        "how_to_play": "Ubica dónde apareció el objeto o criatura tras observar el mapa.",
        "rules": ["Ubicación correcta suma.", "Respuesta más rápida puede ganar bonus."],
        "points": {"correct": 100, "fastest_bonus": 40},
    },
    "hechizo_incompleto": {
        "name": "Hechizo Incompleto",
        "status": "implemented",
        "mode": "quiz",
        "about": "Completa hechizos y frases icónicas a toda velocidad.",
        "how_to_play": "Elige la terminación correcta para completar el hechizo o frase.",
        "rules": ["Solo una terminación correcta.", "Gana quien responda bien más veces."],
        "points": {"correct": 80, "fastest_bonus": 30},
    },
    "artes_ridiculas": {
        "name": "Defensa Contra las Artes Ridículas",
        "status": "implemented",
        "mode": "pattern",
        "about": "Responde ataques absurdos con la acción mágica correcta.",
        "how_to_play": "Lee el ataque y decide entre Ignorar, Bloquear, Contraatacar o Huir.",
        "rules": ["Acierto suma.", "Error resta.", "Rachas pueden dar bonus."],
        "points": {"correct": 100, "wrong": -20, "streak3": 50},
    },
    "caldero_mentiroso": {
        "name": "El Caldero Mentiroso",
        "status": "implemented",
        "mode": "bluff",
        "about": "Decisiones de riesgo: meter o descartar ingredientes para evitar explosiones.",
        "how_to_play": "Analiza el contexto y decide si agregas o descartas el ingrediente.",
        "rules": ["Buen ingrediente metido suma.", "Ingrediente peligroso penaliza."],
        "points": {"house_perfect": 150, "bad_ingredient": -50, "successful_bluff": 80},
    },
    "patronus_personalizado": {
        "name": "Patronus Personalizado",
        "status": "implemented",
        "mode": "text_vote",
        "about": "Ronda social: gana quien reciba más votos por su idea más divertida.",
        "how_to_play": "Lee el prompt y vota por la opción más graciosa de los jugadores.",
        "rules": ["No hay empates forzados.", "Cada voto otorga puntos."],
        "points": {"first": 120, "second": 80, "vote_received": 10},
    },
    "copa_final": {
        "name": "Copa de las Casas: Pregunta Final",
        "status": "implemented",
        "mode": "wager",
        "about": "Pregunta final con lógica de apuesta para remontadas épicas.",
        "how_to_play": "Resuelve la pregunta y administra tu riesgo de puntos.",
        "rules": ["Acierto multiplica apuesta.", "Fallo resta lo apostado (si aplica)."],
        "points": {"bet_levels": [0, 100, 200, 300]},
    },
}
